name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/soundscape .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/soundscape

  deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull image from docker hub
          run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/soundscape:latest

        - name: Remove docker container
          run: sudo docker rm -f soundscape || true

        - name: Run docker container
          run: sudo docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e ACR_ACCESS_KEY=${{ secrets.ACR_ACCESS_KEY }} -e ACR_ACCESS_SECRET=${{ secrets.ACR_ACCESS_SECRET }} -e ACR_HOST=${{ secrets.ACR_HOST }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_ACCESS_KEY_SECRET=${{ secrets.AWS_ACCESS_KEY_SECRET }} --name soundscape ${{ secrets.DOCKER_USERNAME }}/soundscape:latest
